# Generated by Django 3.2.15 on 2026-07-13 06:20

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_project_screenplay'),
        ('models', '0003_auto_20260320_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIBudgetPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='策略名称')),
                ('currency', models.CharField(default='CNY', max_length=3, verbose_name='币种')),
                ('period_type', models.CharField(choices=[('day', '每日'), ('month', '每月'), ('project', '项目周期'), ('lifetime', '永久')], default='project', max_length=20, verbose_name='预算周期')),
                ('soft_limit', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='软限额')),
                ('hard_limit', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='硬限额')),
                ('spent_amount', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18, verbose_name='已结算金额')),
                ('reserved_amount', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18, verbose_name='已预留金额')),
                ('allow_overage', models.BooleanField(default=False, verbose_name='允许超额结算')),
                ('exhausted_action', models.CharField(choices=[('block', '阻断'), ('local_only', '仅本地模型'), ('warn', '仅告警')], default='block', max_length=20, verbose_name='额度耗尽动作')),
                ('reservation_ttl_seconds', models.PositiveIntegerField(default=1800, verbose_name='预留有效期秒数')),
                ('period_started_at', models.DateTimeField(blank=True, null=True, verbose_name='周期开始时间')),
                ('period_ends_at', models.DateTimeField(blank=True, null=True, verbose_name='周期结束时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'db_table': 'inference_budget_policies',
            },
        ),
        migrations.CreateModel(
            name='BudgetReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idempotency_key', models.CharField(max_length=120, verbose_name='幂等键')),
                ('status', models.CharField(choices=[('active', '已预留'), ('settled', '已结算'), ('released', '已释放'), ('expired', '已过期')], default='active', max_length=20, verbose_name='状态')),
                ('estimated_amount', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='预估金额')),
                ('reserved_amount', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='预留金额')),
                ('settled_amount', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18, verbose_name='结算金额')),
                ('currency', models.CharField(default='CNY', max_length=3, verbose_name='币种')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('settled_at', models.DateTimeField(blank=True, null=True, verbose_name='结算时间')),
                ('released_at', models.DateTimeField(blank=True, null=True, verbose_name='释放时间')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='预留详情')),
            ],
            options={
                'db_table': 'inference_budget_reservations',
            },
        ),
        migrations.CreateModel(
            name='GenerationProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=100, unique=True, verbose_name='配置标识')),
                ('name', models.CharField(max_length=120, verbose_name='配置名称')),
                ('capability', models.CharField(choices=[('llm', '文本生成'), ('text2image', '文生图'), ('image_edit', '图片编辑'), ('image2video', '图生视频'), ('embedding', '向量化'), ('speech', '语音')], max_length=20, verbose_name='生成能力')),
                ('model_name', models.CharField(blank=True, default='', max_length=255, verbose_name='默认模型')),
                ('default_parameters', models.JSONField(blank=True, default=dict, verbose_name='默认参数')),
                ('hard_limits', models.JSONField(blank=True, default=dict, verbose_name='参数硬限制')),
                ('allowed_parameters', models.JSONField(blank=True, default=list, verbose_name='允许覆盖的参数')),
                ('description', models.TextField(blank=True, default='', verbose_name='说明')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'db_table': 'inference_generation_profiles',
                'ordering': ['capability', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GenerationRoute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='路由名称')),
                ('capability', models.CharField(choices=[('llm', '文本生成'), ('text2image', '文生图'), ('image_edit', '图片编辑'), ('image2video', '图生视频'), ('embedding', '向量化'), ('speech', '语音')], max_length=20, verbose_name='生成能力')),
                ('priority', models.IntegerField(default=0, verbose_name='路由优先级')),
                ('match_rules', models.JSONField(blank=True, default=dict, verbose_name='匹配规则')),
                ('local_first', models.BooleanField(default=True, verbose_name='本地节点优先')),
                ('fallback_error_classes', models.JSONField(blank=True, default=list, verbose_name='允许回退的错误分类')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'db_table': 'inference_generation_routes',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GenerationTarget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='目标名称')),
                ('priority', models.IntegerField(default=0, verbose_name='目标优先级')),
                ('weight', models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=10, verbose_name='权重')),
                ('parameter_overrides', models.JSONField(blank=True, default=dict, verbose_name='目标参数覆盖')),
                ('max_concurrency', models.PositiveIntegerField(default=1, verbose_name='目标并发上限')),
                ('cooldown_until', models.DateTimeField(blank=True, null=True, verbose_name='冷却截止时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'db_table': 'inference_generation_targets',
                'ordering': ['-priority', '-weight', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GenerationWorkItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capability', models.CharField(choices=[('llm', '文本生成'), ('text2image', '文生图'), ('image_edit', '图片编辑'), ('image2video', '图生视频'), ('embedding', '向量化'), ('speech', '语音')], max_length=20, verbose_name='生成能力')),
                ('stage_type', models.CharField(blank=True, default='', max_length=40, verbose_name='业务阶段')),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='幂等键')),
                ('status', models.CharField(choices=[('created', '已创建'), ('reserved', '已预留预算'), ('queued', '已入队'), ('running', '执行中'), ('succeeded', '成功'), ('failed', '失败'), ('cancelled', '已取消')], default='created', max_length=20, verbose_name='状态')),
                ('priority', models.IntegerField(default=0, verbose_name='优先级')),
                ('request_parameters', models.JSONField(blank=True, default=dict, verbose_name='请求参数')),
                ('effective_parameters', models.JSONField(blank=True, default=dict, verbose_name='生效参数')),
                ('usage', models.JSONField(blank=True, default=dict, verbose_name='计费用量')),
                ('estimated_cost', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18, verbose_name='预估成本')),
                ('actual_cost', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18, verbose_name='实际成本')),
                ('currency', models.CharField(default='CNY', max_length=3, verbose_name='币种')),
                ('provider_request_id', models.CharField(blank=True, default='', max_length=255, verbose_name='厂商请求 ID')),
                ('attempt_count', models.PositiveIntegerField(default=0, verbose_name='尝试次数')),
                ('max_attempts', models.PositiveIntegerField(default=1, verbose_name='最大尝试次数')),
                ('error_class', models.CharField(blank=True, default='', max_length=40, verbose_name='错误分类')),
                ('error_code', models.CharField(blank=True, default='', max_length=120, verbose_name='错误码')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='计划执行时间')),
                ('claimed_at', models.DateTimeField(blank=True, null=True, verbose_name='领取时间')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
            ],
            options={
                'db_table': 'inference_generation_work_items',
                'ordering': ['-priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('text', '文本'), ('image', '图片'), ('video', '视频'), ('audio', '音频'), ('metadata', '元数据')], max_length=20, verbose_name='工件类型')),
                ('status', models.CharField(choices=[('pending', '待写入'), ('ready', '可用'), ('failed', '失败'), ('deleted', '已删除')], default='pending', max_length=20, verbose_name='状态')),
                ('uri', models.CharField(max_length=1024, verbose_name='工件地址')),
                ('storage_backend', models.CharField(default='local', max_length=40, verbose_name='存储后端')),
                ('mime_type', models.CharField(blank=True, default='', max_length=120, verbose_name='MIME 类型')),
                ('checksum', models.CharField(blank=True, default='', max_length=128, verbose_name='校验值')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='文件大小字节')),
                ('width', models.PositiveIntegerField(default=0, verbose_name='宽度')),
                ('height', models.PositiveIntegerField(default=0, verbose_name='高度')),
                ('duration_seconds', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, verbose_name='时长秒数')),
                ('fps', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=8, verbose_name='帧率')),
                ('segment_index', models.PositiveIntegerField(blank=True, null=True, verbose_name='分段序号')),
                ('segment_start', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='分段开始秒')),
                ('segment_end', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='分段结束秒')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='工件元数据')),
            ],
            options={
                'db_table': 'inference_media_artifacts',
                'ordering': ['work_item', 'segment_index', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectAISettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capability_routes', models.JSONField(blank=True, default=dict, verbose_name='能力路由映射')),
                ('parameter_overrides', models.JSONField(blank=True, default=dict, verbose_name='项目参数覆盖')),
                ('prefer_local', models.BooleanField(default=True, verbose_name='优先本地推理')),
                ('allow_paid_fallback', models.BooleanField(default=False, verbose_name='允许付费回退')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'db_table': 'inference_project_settings',
            },
        ),
        migrations.CreateModel(
            name='ProviderPriceRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capability', models.CharField(choices=[('llm', '文本生成'), ('text2image', '文生图'), ('image_edit', '图片编辑'), ('image2video', '图生视频'), ('embedding', '向量化'), ('speech', '语音')], max_length=20, verbose_name='生成能力')),
                ('model_pattern', models.CharField(default='*', max_length=255, verbose_name='模型匹配模式')),
                ('billing_unit', models.CharField(choices=[('input_token', '输入 Token'), ('output_token', '输出 Token'), ('token', '总 Token'), ('image', '图片张数'), ('image_megapixel', '图片百万像素'), ('video_second', '视频秒数'), ('request', '请求次数'), ('gpu_second', 'GPU 秒数')], max_length=30, verbose_name='计费单位')),
                ('unit_size', models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=20, verbose_name='单位基数')),
                ('unit_price', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='单位价格')),
                ('minimum_charge', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20, verbose_name='最低收费')),
                ('currency', models.CharField(default='CNY', max_length=3, verbose_name='币种')),
                ('priority', models.IntegerField(default=0, verbose_name='匹配优先级')),
                ('effective_from', models.DateTimeField(blank=True, null=True, verbose_name='生效时间')),
                ('effective_to', models.DateTimeField(blank=True, null=True, verbose_name='失效时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='计价元数据')),
            ],
            options={
                'db_table': 'inference_provider_price_rates',
                'ordering': ['-priority', '-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='RuntimeNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='节点名称')),
                ('node_type', models.CharField(choices=[('local_gpu', '本地 GPU'), ('rented_gpu', '租用 GPU'), ('remote_api', '远端 API'), ('cpu', 'CPU 节点'), ('edge', '边缘节点')], max_length=20, verbose_name='节点类型')),
                ('endpoint', models.URLField(blank=True, default='', max_length=500, verbose_name='服务地址')),
                ('credential_ref', models.CharField(blank=True, default='', help_text='仅保存密钥管理器引用，不保存原始密钥。', max_length=255, verbose_name='凭据引用')),
                ('capabilities', models.JSONField(blank=True, default=list, verbose_name='支持能力')),
                ('health_status', models.CharField(choices=[('unknown', '未知'), ('healthy', '健康'), ('degraded', '降级'), ('unavailable', '不可用')], default='unknown', max_length=20, verbose_name='健康状态')),
                ('concurrency_limit', models.PositiveIntegerField(default=1, verbose_name='并发上限')),
                ('priority', models.IntegerField(default=0, verbose_name='节点优先级')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='节点元数据')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='最后在线时间')),
            ],
            options={
                'db_table': 'inference_runtime_nodes',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='runtimenode',
            index=models.Index(fields=['is_active', 'health_status', '-priority'], name='inf_node_health_idx'),
        ),
        migrations.AddField(
            model_name='providerpricerate',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_rates', to='models.modelprovider', verbose_name='模型提供商'),
        ),
        migrations.AddField(
            model_name='providerpricerate',
            name='runtime_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_rates', to='inference.runtimenode', verbose_name='运行节点'),
        ),
        migrations.AddField(
            model_name='projectaisettings',
            name='budget_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_settings', to='inference.aibudgetpolicy', verbose_name='预算策略'),
        ),
        migrations.AddField(
            model_name='projectaisettings',
            name='default_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_settings', to='inference.generationprofile', verbose_name='默认生成配置'),
        ),
        migrations.AddField(
            model_name='projectaisettings',
            name='default_route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_settings', to='inference.generationroute', verbose_name='默认路由'),
        ),
        migrations.AddField(
            model_name='projectaisettings',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_settings', to='projects.project', verbose_name='项目'),
        ),
        migrations.AddField(
            model_name='mediaartifact',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_artifacts', to='projects.project', verbose_name='项目'),
        ),
        migrations.AddField(
            model_name='mediaartifact',
            name='work_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='inference.generationworkitem', verbose_name='工作项'),
        ),
        migrations.AddField(
            model_name='generationworkitem',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_items', to='inference.generationprofile', verbose_name='生成配置'),
        ),
        migrations.AddField(
            model_name='generationworkitem',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_work_items', to='projects.project', verbose_name='项目'),
        ),
        migrations.AddField(
            model_name='generationworkitem',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_work_items', to='models.modelprovider', verbose_name='模型提供商'),
        ),
        migrations.AddField(
            model_name='generationworkitem',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_items', to='inference.generationroute', verbose_name='命中路由'),
        ),
        migrations.AddField(
            model_name='generationworkitem',
            name='runtime_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_items', to='inference.runtimenode', verbose_name='运行节点'),
        ),
        migrations.AddField(
            model_name='generationworkitem',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_items', to='inference.generationtarget', verbose_name='命中目标'),
        ),
        migrations.AddField(
            model_name='generationtarget',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targets', to='inference.generationprofile', verbose_name='目标生成配置'),
        ),
        migrations.AddField(
            model_name='generationtarget',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inference_targets', to='models.modelprovider', verbose_name='模型提供商'),
        ),
        migrations.AddField(
            model_name='generationtarget',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='inference.generationroute', verbose_name='所属路由'),
        ),
        migrations.AddField(
            model_name='generationtarget',
            name='runtime_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_targets', to='inference.runtimenode', verbose_name='运行节点'),
        ),
        migrations.AddField(
            model_name='generationroute',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to='inference.generationprofile', verbose_name='默认生成配置'),
        ),
        migrations.AddIndex(
            model_name='generationprofile',
            index=models.Index(fields=['capability', 'is_active'], name='inf_profile_cap_idx'),
        ),
        migrations.AddField(
            model_name='budgetreservation',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='inference.aibudgetpolicy', verbose_name='预算策略'),
        ),
        migrations.AddField(
            model_name='budgetreservation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_reservations', to='projects.project', verbose_name='项目'),
        ),
        migrations.AddField(
            model_name='budgetreservation',
            name='work_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_reservations', to='inference.generationworkitem', verbose_name='工作项'),
        ),
        migrations.AddIndex(
            model_name='aibudgetpolicy',
            index=models.Index(fields=['is_active', 'period_ends_at'], name='inf_budget_active_idx'),
        ),
        migrations.AddIndex(
            model_name='providerpricerate',
            index=models.Index(fields=['capability', 'billing_unit', 'is_active', '-priority'], name='inf_price_match_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaartifact',
            index=models.Index(fields=['work_item', 'kind', 'status'], name='inf_artifact_work_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaartifact',
            index=models.Index(fields=['project', 'kind', 'created_at'], name='inf_artifact_proj_idx'),
        ),
        migrations.AddIndex(
            model_name='generationworkitem',
            index=models.Index(fields=['status', '-priority', 'created_at'], name='inf_work_queue_idx'),
        ),
        migrations.AddIndex(
            model_name='generationworkitem',
            index=models.Index(fields=['project', 'capability', 'status'], name='inf_work_project_idx'),
        ),
        migrations.AddIndex(
            model_name='generationworkitem',
            index=models.Index(fields=['provider_request_id'], name='inf_work_request_idx'),
        ),
        migrations.AddIndex(
            model_name='generationtarget',
            index=models.Index(fields=['route', 'is_active', '-priority'], name='inf_target_route_idx'),
        ),
        migrations.AddConstraint(
            model_name='generationtarget',
            constraint=models.CheckConstraint(check=models.Q(('provider__isnull', False), ('runtime_node__isnull', False), _connector='OR'), name='inf_target_has_destination'),
        ),
        migrations.AlterUniqueTogether(
            name='generationtarget',
            unique_together={('route', 'name')},
        ),
        migrations.AddIndex(
            model_name='generationroute',
            index=models.Index(fields=['capability', 'is_active', '-priority'], name='inf_route_cap_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetreservation',
            index=models.Index(fields=['policy', 'status', 'expires_at'], name='inf_reserve_policy_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetreservation',
            index=models.Index(fields=['project', 'status'], name='inf_reserve_project_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='budgetreservation',
            unique_together={('policy', 'idempotency_key')},
        ),
    ]
