# Generated by Django 3.2.15 on 2026-07-13 06:32

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_project_screenplay'),
        ('inference', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generationtarget',
            options={'ordering': ['position', '-priority', '-weight', 'name']},
        ),
        migrations.AddField(
            model_name='aibudgetpolicy',
            name='daily_limit_cny',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18, verbose_name='全局每日预算（CNY）'),
        ),
        migrations.AddField(
            model_name='aibudgetpolicy',
            name='monthly_limit_cny',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18, verbose_name='全局每月预算（CNY）'),
        ),
        migrations.AddField(
            model_name='aibudgetpolicy',
            name='tooling_limit_cny',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18, verbose_name='全局工具预算（CNY）'),
        ),
        migrations.AddField(
            model_name='generationroute',
            name='profile_code',
            field=models.CharField(choices=[('draft', '草稿'), ('balanced', '均衡'), ('final', '成片')], default='balanced', max_length=20, verbose_name='生成档位'),
        ),
        migrations.AddField(
            model_name='generationroute',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generation_routes', to='projects.project', verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='generationroute',
            name='scope',
            field=models.CharField(choices=[('global', '全局'), ('project', '项目')], default='global', max_length=20, verbose_name='作用域'),
        ),
        migrations.AddField(
            model_name='generationroute',
            name='stage_type',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='业务阶段'),
        ),
        migrations.AddField(
            model_name='generationtarget',
            name='max_attempts',
            field=models.PositiveIntegerField(default=1, verbose_name='最大尝试次数'),
        ),
        migrations.AddField(
            model_name='generationtarget',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='路由位置'),
        ),
        migrations.AddField(
            model_name='generationtarget',
            name='role',
            field=models.CharField(choices=[('local_primary', '本地主目标'), ('local_secondary', '本地备目标'), ('paid_fallback', '付费回退')], default='local_primary', max_length=30, verbose_name='目标角色'),
        ),
        migrations.AddField(
            model_name='generationtarget',
            name='timeout_seconds',
            field=models.PositiveIntegerField(default=300, verbose_name='超时秒数'),
        ),
        migrations.AddField(
            model_name='generationworkitem',
            name='agent_job_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Runtime Agent Job ID'),
        ),
        migrations.AddField(
            model_name='generationworkitem',
            name='heartbeat_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后心跳时间'),
        ),
        migrations.AddField(
            model_name='generationworkitem',
            name='lease_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='租约截止时间'),
        ),
        migrations.AddField(
            model_name='generationworkitem',
            name='lease_owner',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='租约持有者'),
        ),
        migrations.AddField(
            model_name='generationworkitem',
            name='next_retry_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='下次重试时间'),
        ),
        migrations.AddField(
            model_name='generationworkitem',
            name='route_snapshot',
            field=models.JSONField(blank=True, default=dict, verbose_name='路由快照'),
        ),
        migrations.AddField(
            model_name='generationworkitem',
            name='segment_index',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='分段序号'),
        ),
        migrations.AddField(
            model_name='generationworkitem',
            name='storyboard_id',
            field=models.UUIDField(blank=True, null=True, verbose_name='分镜 ID'),
        ),
        migrations.AddField(
            model_name='generationworkitem',
            name='tile_index',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='切片序号'),
        ),
        migrations.AddField(
            model_name='generationworkitem',
            name='version',
            field=models.PositiveIntegerField(default=0, verbose_name='状态版本'),
        ),
        migrations.AddField(
            model_name='mediaartifact',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='删除时间'),
        ),
        migrations.AddField(
            model_name='mediaartifact',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='过期时间'),
        ),
        migrations.AddField(
            model_name='mediaartifact',
            name='lifecycle',
            field=models.CharField(choices=[('source', '源素材'), ('intermediate', '中间产物'), ('failed', '失败隔离产物'), ('final', '最终产物')], default='intermediate', max_length=20, verbose_name='生命周期'),
        ),
        migrations.AddField(
            model_name='mediaartifact',
            name='protected',
            field=models.BooleanField(default=False, verbose_name='受保护'),
        ),
        migrations.AddField(
            model_name='mediaartifact',
            name='quarantined',
            field=models.BooleanField(default=False, verbose_name='已隔离'),
        ),
        migrations.AddField(
            model_name='mediaartifact',
            name='sha256',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='SHA-256'),
        ),
        migrations.AddField(
            model_name='projectaisettings',
            name='allow_cloud_data_transfer',
            field=models.BooleanField(default=False, verbose_name='允许素材出站'),
        ),
        migrations.AddField(
            model_name='projectaisettings',
            name='cloud_authorized_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='出站授权时间'),
        ),
        migrations.AddField(
            model_name='projectaisettings',
            name='cloud_authorized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_ai_cloud_projects', to=settings.AUTH_USER_MODEL, verbose_name='出站授权人'),
        ),
        migrations.AddField(
            model_name='projectaisettings',
            name='default_profile_code',
            field=models.CharField(choices=[('draft', '草稿'), ('balanced', '均衡'), ('final', '成片')], default='balanced', max_length=20, verbose_name='默认生成档位'),
        ),
        migrations.AddField(
            model_name='projectaisettings',
            name='project_budget_cny',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18, verbose_name='项目付费预算（CNY）'),
        ),
        migrations.AddField(
            model_name='providerpricerate',
            name='conditions',
            field=models.JSONField(blank=True, default=dict, verbose_name='附加计价条件'),
        ),
        migrations.AddField(
            model_name='providerpricerate',
            name='exchange_rate_to_cny',
            field=models.DecimalField(decimal_places=8, default=Decimal('1'), max_digits=20, verbose_name='折算人民币汇率'),
        ),
        migrations.AddField(
            model_name='providerpricerate',
            name='source_note',
            field=models.TextField(blank=True, default='', verbose_name='价格来源说明'),
        ),
        migrations.AddField(
            model_name='providerpricerate',
            name='version',
            field=models.CharField(default='v1', max_length=64, verbose_name='价格版本'),
        ),
        migrations.AddField(
            model_name='runtimenode',
            name='access_token',
            field=models.CharField(blank=True, default='', help_text='当前兼容字段为明文；输出和日志必须经过敏感字段遮罩。', max_length=512, verbose_name='Runtime Agent 访问令牌'),
        ),
        migrations.AddField(
            model_name='runtimenode',
            name='agent_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Runtime Agent 地址'),
        ),
        migrations.AddField(
            model_name='runtimenode',
            name='agent_version',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Agent 版本'),
        ),
        migrations.AddField(
            model_name='runtimenode',
            name='hardware_snapshot',
            field=models.JSONField(blank=True, default=dict, verbose_name='硬件快照'),
        ),
        migrations.AddField(
            model_name='runtimenode',
            name='is_local',
            field=models.BooleanField(default=True, verbose_name='是否本机节点'),
        ),
        migrations.AddField(
            model_name='runtimenode',
            name='reserved_slot_count',
            field=models.PositiveIntegerField(default=0, verbose_name='保留槽位数'),
        ),
        migrations.AddField(
            model_name='runtimenode',
            name='resource_groups',
            field=models.JSONField(blank=True, default=dict, verbose_name='资源组容量'),
        ),
        migrations.AddField(
            model_name='runtimenode',
            name='slot_config',
            field=models.JSONField(blank=True, default=dict, verbose_name='槽位配置'),
        ),
        migrations.AddField(
            model_name='runtimenode',
            name='slot_count',
            field=models.PositiveIntegerField(default=1, verbose_name='总槽位数'),
        ),
        migrations.AlterField(
            model_name='aibudgetpolicy',
            name='hard_limit',
            field=models.DecimalField(blank=True, decimal_places=6, default=Decimal('0'), max_digits=18, null=True, verbose_name='硬限额'),
        ),
        migrations.AlterField(
            model_name='budgetreservation',
            name='status',
            field=models.CharField(choices=[('active', '已预留'), ('settled', '已结算'), ('released', '已释放'), ('expired', '已过期'), ('ambiguous', '结果不明确'), ('manual_review', '等待人工复核')], default='active', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='generationworkitem',
            name='idempotency_key',
            field=models.CharField(default=uuid.uuid4, max_length=128, verbose_name='幂等键'),
        ),
        migrations.AlterField(
            model_name='generationworkitem',
            name='status',
            field=models.CharField(choices=[('waiting', '等待认领'), ('leased', '已租约认领'), ('running', '执行中'), ('retry_wait', '等待重试'), ('succeeded', '成功'), ('failed', '失败'), ('cancelled', '已取消')], default='waiting', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='providerpricerate',
            name='billing_unit',
            field=models.CharField(choices=[('input_token', '输入 Token'), ('output_token', '输出 Token'), ('token', '总 Token'), ('image', '图片张数'), ('image_megapixel', '图片百万像素'), ('video_second', '视频秒数'), ('video_task', '视频任务数'), ('request', '请求次数'), ('gpu_second', 'GPU 秒数')], max_length=30, verbose_name='计费单位'),
        ),
        migrations.AlterUniqueTogether(
            name='generationworkitem',
            unique_together={('project', 'idempotency_key')},
        ),
        migrations.AddIndex(
            model_name='generationworkitem',
            index=models.Index(fields=['status', 'lease_expires_at'], name='inf_work_lease_idx'),
        ),
        migrations.AddIndex(
            model_name='generationworkitem',
            index=models.Index(fields=['status', 'next_retry_at'], name='inf_work_retry_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaartifact',
            index=models.Index(fields=['lifecycle', 'expires_at'], name='inf_artifact_life_idx'),
        ),
    ]
