# Generated by Django 3.2.15 on 2026-07-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inference', '0002_approved_contract_alignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generationprofile',
            name='capability',
            field=models.CharField(choices=[('llm', '文本生成'), ('text2image', '文生图'), ('image_edit', '图片编辑'), ('image2video', '图生视频'), ('motion_render', '非生成式视频运镜'), ('embedding', '向量化'), ('speech', '语音')], max_length=20, verbose_name='生成能力'),
        ),
        migrations.AlterField(
            model_name='generationprofile',
            name='key',
            field=models.SlugField(max_length=100, verbose_name='配置标识'),
        ),
        migrations.AlterField(
            model_name='generationroute',
            name='capability',
            field=models.CharField(choices=[('llm', '文本生成'), ('text2image', '文生图'), ('image_edit', '图片编辑'), ('image2video', '图生视频'), ('motion_render', '非生成式视频运镜'), ('embedding', '向量化'), ('speech', '语音')], max_length=20, verbose_name='生成能力'),
        ),
        migrations.AlterField(
            model_name='generationworkitem',
            name='capability',
            field=models.CharField(choices=[('llm', '文本生成'), ('text2image', '文生图'), ('image_edit', '图片编辑'), ('image2video', '图生视频'), ('motion_render', '非生成式视频运镜'), ('embedding', '向量化'), ('speech', '语音')], max_length=20, verbose_name='生成能力'),
        ),
        migrations.AlterField(
            model_name='providerpricerate',
            name='capability',
            field=models.CharField(choices=[('llm', '文本生成'), ('text2image', '文生图'), ('image_edit', '图片编辑'), ('image2video', '图生视频'), ('motion_render', '非生成式视频运镜'), ('embedding', '向量化'), ('speech', '语音')], max_length=20, verbose_name='生成能力'),
        ),
        migrations.AddConstraint(
            model_name='generationprofile',
            constraint=models.UniqueConstraint(fields=('capability', 'key'), name='inf_profile_capability_key_uniq'),
        ),
    ]
