# Generated by Django 3.2.15 on 2026-07-13 07:37

from django.db import migrations, models
from django.db.models import Count
import uuid


def deduplicate_media_artifacts(apps, schema_editor):
    """加唯一约束前合并历史竞态产生的同工作项同 URI 记录。"""

    MediaArtifact = apps.get_model('inference', 'MediaArtifact')
    referencing_models = [
        apps.get_model('content', 'GeneratedImage'),
        apps.get_model('content', 'GeneratedVideo'),
        apps.get_model('content', 'EditedImage'),
    ]
    duplicate_keys = MediaArtifact.objects.values('work_item_id', 'uri').annotate(
        total=Count('id')
    ).filter(total__gt=1)
    for key in duplicate_keys.iterator():
        artifacts = list(
            MediaArtifact.objects.filter(
                work_item_id=key['work_item_id'], uri=key['uri']
            ).order_by('created_at', 'id')
        )
        keep = artifacts[0]
        duplicate_ids = [artifact.id for artifact in artifacts[1:]]
        for model in referencing_models:
            model.objects.filter(media_artifact_id__in=duplicate_ids).update(
                media_artifact_id=keep.id
            )
        MediaArtifact.objects.filter(id__in=duplicate_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20260713_1452'),
        ('inference', '0004_seed_safe_local_ai_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationworkitem',
            name='depends_on',
            field=models.ManyToManyField(blank=True, related_name='dependent_work_items', to='inference.GenerationWorkItem', verbose_name='前置工作项'),
        ),
        migrations.AddField(
            model_name='generationworkitem',
            name='projected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='业务投影时间'),
        ),
        migrations.AddField(
            model_name='generationworkitem',
            name='projection_error',
            field=models.TextField(blank=True, default='', verbose_name='业务投影错误'),
        ),
        migrations.AddField(
            model_name='generationworkitem',
            name='projection_status',
            field=models.CharField(choices=[('pending', '等待投影'), ('completed', '投影完成'), ('failed', '投影失败')], default='pending', max_length=20, verbose_name='业务投影状态'),
        ),
        migrations.AddField(
            model_name='generationworkitem',
            name='stage_execution_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, verbose_name='阶段执行批次'),
        ),
        migrations.AddIndex(
            model_name='generationworkitem',
            index=models.Index(fields=['project', 'stage_type', 'stage_execution_id'], name='inf_work_stage_exec_idx'),
        ),
        migrations.RunPython(deduplicate_media_artifacts, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='mediaartifact',
            constraint=models.UniqueConstraint(fields=('work_item', 'uri'), name='inf_artifact_work_uri_uniq'),
        ),
    ]
