# Generated by Django 3.2.15 on 2026-07-13 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inference', '0001_initial'),
        ('models', '0003_auto_20260320_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelprovider',
            name='deployment_mode',
            field=models.CharField(choices=[('mock', 'Mock'), ('local', '本地'), ('api', 'API')], default='api', max_length=10, verbose_name='部署模式'),
        ),
        migrations.AddField(
            model_name='modelprovider',
            name='health_status',
            field=models.CharField(choices=[('unknown', '未知'), ('healthy', '健康'), ('degraded', '降级'), ('unavailable', '不可用')], default='unknown', max_length=20, verbose_name='健康状态'),
        ),
        migrations.AddField(
            model_name='modelprovider',
            name='runtime_adapter',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Runtime适配器'),
        ),
        migrations.AddField(
            model_name='modelprovider',
            name='runtime_model_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Runtime模型ID'),
        ),
        migrations.AddField(
            model_name='modelprovider',
            name='runtime_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='providers', to='inference.runtimenode', verbose_name='Runtime节点'),
        ),
        migrations.AddField(
            model_name='modelprovider',
            name='supports_cloud_fallback',
            field=models.BooleanField(default=False, verbose_name='允许作为云端回退目标'),
        ),
        migrations.AlterField(
            model_name='modelprovider',
            name='api_key',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='API密钥'),
        ),
        migrations.AlterField(
            model_name='modelprovider',
            name='api_url',
            field=models.URLField(blank=True, default='', verbose_name='API地址'),
        ),
    ]
