# Generated by Django 3.2.15 on 2026-07-13 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inference', '0002_approved_contract_alignment'),
        ('models', '0004_auto_20260713_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelusagelog',
            name='attempt_number',
            field=models.PositiveIntegerField(default=1, verbose_name='尝试序号'),
        ),
        migrations.AddField(
            model_name='modelusagelog',
            name='currency',
            field=models.CharField(default='CNY', max_length=3, verbose_name='币种'),
        ),
        migrations.AddField(
            model_name='modelusagelog',
            name='deployment_mode',
            field=models.CharField(default='api', max_length=10, verbose_name='部署模式'),
        ),
        migrations.AddField(
            model_name='modelusagelog',
            name='error_code',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='标准错误码'),
        ),
        migrations.AddField(
            model_name='modelusagelog',
            name='estimated_cost',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18, verbose_name='预计成本'),
        ),
        migrations.AddField(
            model_name='modelusagelog',
            name='fallback_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fallback_source_logs', to='models.modelprovider', verbose_name='回退来源'),
        ),
        migrations.AddField(
            model_name='modelusagelog',
            name='fallback_reason',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='回退原因'),
        ),
        migrations.AddField(
            model_name='modelusagelog',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='结束时间'),
        ),
        migrations.AddField(
            model_name='modelusagelog',
            name='idempotency_key',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='幂等键'),
        ),
        migrations.AddField(
            model_name='modelusagelog',
            name='image_count',
            field=models.IntegerField(default=0, verbose_name='图片数量'),
        ),
        migrations.AddField(
            model_name='modelusagelog',
            name='input_tokens',
            field=models.IntegerField(default=0, verbose_name='输入Token数'),
        ),
        migrations.AddField(
            model_name='modelusagelog',
            name='media_dimensions',
            field=models.JSONField(blank=True, default=list, verbose_name='媒体尺寸'),
        ),
        migrations.AddField(
            model_name='modelusagelog',
            name='media_hashes',
            field=models.JSONField(blank=True, default=list, verbose_name='媒体哈希'),
        ),
        migrations.AddField(
            model_name='modelusagelog',
            name='output_tokens',
            field=models.IntegerField(default=0, verbose_name='输出Token数'),
        ),
        migrations.AddField(
            model_name='modelusagelog',
            name='price_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_logs', to='inference.providerpricerate', verbose_name='价目表版本'),
        ),
        migrations.AddField(
            model_name='modelusagelog',
            name='request_summary',
            field=models.JSONField(blank=True, default=dict, verbose_name='脱敏请求摘要'),
        ),
        migrations.AddField(
            model_name='modelusagelog',
            name='runtime_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_logs', to='inference.runtimenode', verbose_name='Runtime节点'),
        ),
        migrations.AddField(
            model_name='modelusagelog',
            name='settled_cost',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18, verbose_name='结算成本'),
        ),
        migrations.AddField(
            model_name='modelusagelog',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开始时间'),
        ),
        migrations.AddField(
            model_name='modelusagelog',
            name='video_seconds',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='视频秒数'),
        ),
        migrations.AddField(
            model_name='modelusagelog',
            name='work_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_logs', to='inference.generationworkitem', verbose_name='工作项'),
        ),
    ]
