# Generated by Django 3.2.15 on 2026-07-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_auto_20260713_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelprovider',
            name='provider_type',
            field=models.CharField(choices=[('llm', 'LLM模型'), ('text2image', '文生图模型'), ('image2video', '图生视频模型'), ('image_edit', '图片编辑模型'), ('motion_render', '非生成式视频运镜')], max_length=20, verbose_name='模型作用分类'),
        ),
        migrations.AlterField(
            model_name='vendorconnectionconfig',
            name='capability',
            field=models.CharField(choices=[('llm', 'LLM模型'), ('text2image', '文生图模型'), ('image2video', '图生视频模型'), ('image_edit', '图片编辑模型'), ('motion_render', '非生成式视频运镜')], max_length=20, verbose_name='模型能力'),
        ),
    ]
