# Generated by Django 3.2.15 on 2026-07-13 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inference', '0002_approved_contract_alignment'),
        ('content', '0002_unify_camera_movement_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='editedimage',
            name='media_artifact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_images', to='inference.mediaartifact', verbose_name='统一媒体产物'),
        ),
        migrations.AddField(
            model_name='generatedimage',
            name='media_artifact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_images', to='inference.mediaartifact', verbose_name='统一媒体产物'),
        ),
        migrations.AddField(
            model_name='generatedvideo',
            name='media_artifact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_videos', to='inference.mediaartifact', verbose_name='统一媒体产物'),
        ),
    ]
